name: empatools

dependencies:
  - python=3.11
  # pandas and scientific python
  - click
  - numpy
  - matplotlib
  - scipy
  - h5py
  - pandas
  - scikit-learn
  - colorcet
  - xlrd
  - openpyxl
  - periodictable
  # Tools
  - jupyter
  - jupyterlab
  - jupyterlab-spellchecker
  - jupyterlab_code_formatter
  - isort
  - black
  - ipykernel
  - pip
  - pip:
    - -e . # install the local empatools package

# mamba env create -f environment.yml
# python -m ipykernel install --user --name empatools

# mamba activate empatools

# mamba deactivate empatools
# mamba remove -n pyrolite
# jupyter kernelspec uninstall empatools
